/**
 * Các trạng thái của Resume (hồ sơ ứng tuyển)
 */
export const RESUME_STATUS = {
  PENDING: 'PENDING', // Mới apply, chờ HR xem
  REVIEWING: 'REVIEWING', // HR đang xem xét
  APPROVED: 'APPROVED', // HR đã duyệt, sẵn sàng hẹn phỏng vấn
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED', // Đã hẹn lịch phỏng vấn
  INTERVIEW_CONFIRMED: 'INTERVIEW_CONFIRMED', // Ứng viên đã xác nhận
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED', // Đã phỏng vấn xong
  INTERVIEW_CANCELLED: 'INTERVIEW_CANCELLED', // Lịch phỏng vấn bị hủy
  OFFERED: 'OFFERED', // Đã offer
  REJECTED: 'REJECTED', // Từ chối
  ACCEPTED: 'ACCEPTED', // Ứng viên chấp nhận offer
  DECLINED: 'DECLINED', // Ứng viên từ chối offer
} as const;

export const RESUME_STATUS_LIST = Object.values(RESUME_STATUS);

/**
 * Luồng chuyển đổi status hợp lệ
 */
export const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
  [RESUME_STATUS.PENDING]: [RESUME_STATUS.REVIEWING, RESUME_STATUS.REJECTED],
  [RESUME_STATUS.REVIEWING]: [
    RESUME_STATUS.APPROVED,
    RESUME_STATUS.REJECTED,
    RESUME_STATUS.PENDING,
  ],
  [RESUME_STATUS.APPROVED]: [
    RESUME_STATUS.INTERVIEW_SCHEDULED,
    RESUME_STATUS.REJECTED,
  ],
  [RESUME_STATUS.INTERVIEW_SCHEDULED]: [
    RESUME_STATUS.INTERVIEW_CONFIRMED,
    RESUME_STATUS.INTERVIEW_CANCELLED,
  ],
  [RESUME_STATUS.INTERVIEW_CONFIRMED]: [
    RESUME_STATUS.INTERVIEW_COMPLETED,
    RESUME_STATUS.INTERVIEW_CANCELLED,
  ],
  [RESUME_STATUS.INTERVIEW_COMPLETED]: [
    RESUME_STATUS.OFFERED,
    RESUME_STATUS.REJECTED,
  ],
  [RESUME_STATUS.OFFERED]: [
    RESUME_STATUS.ACCEPTED,
    RESUME_STATUS.DECLINED,
    RESUME_STATUS.REJECTED,
  ],
  [RESUME_STATUS.INTERVIEW_CANCELLED]: [
    RESUME_STATUS.REVIEWING,
    RESUME_STATUS.APPROVED,
  ],
};





